name: bendium
description: A Chrome extension for talking to Bender.
version: 1.16.1
author: George Lesica <george.lesica@workiva.com>
homepage: https://github.com/georgelesica-wf/bendium

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  barback: ^0.15.2
  chrome: ^0.9.2
  dart_sass_transformer: ^0.5.0
  dart_to_js_script_rewriter: ^1.0.0
  pubspec: ^0.0.14
  react: ^3.0.0
  w_flux: ^2.6.0
  over_react: ^1.9.0
  w_common: ^1.2.0

dev_dependencies:
  browser: any
  dart_dev: ^1.7.0
  dart_style: any
  test: '>=0.12.0 <0.13.0'

transformers:
  - chrome
  - bendium
  - dart_sass_transformer
  - dart_to_js_script_rewriter
  - over_react
  - $dart2js:
      minify: true
      csp: true
  - test/pub_serve:
      $include: test/**_test.dart

