@TestOn('vm')
library test.unit.vm.generated_runner_test;

// Generated by `pub run dart_dev gen-test-runner -d test/unit/vm -e Environment.vm --no-genHtml`

import './action_test.dart' as action_test;
import './actions_test.dart' as actions_test;
import 'package:test/test.dart';

void main() {
  action_test.main();
  actions_test.main();
}
